const CONFIG_LIST = 'CONFIG_LIST'
const URL_SESSION = 'URL_SESSION'
const METHOD_SESSION = 'METHOD_SESSION'
const FORM_LIST = 'FORM_LIST'
const RESULT_SESSION = 'RESULT_SESSION'
const HEADER_FORM_LIST = 'HEADER_FORM_LIST'
const CONFIG_ID = 'CONFIG_ID'

export {
  CONFIG_LIST,
  URL_SESSION,
  METHOD_SESSION,
  FORM_LIST,
  RESULT_SESSION,
  HEADER_FORM_LIST,
  CONFIG_ID
}
